name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_yes_no_solver/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'ovos_yes_no_solver/version.py'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
          python -m pip install build wheel
      - name: Install test dependencies
        run: |
          pip install -r tests.txt
      - name: Install repo
        run: |
          pip install -e .
      - name: Run unittests
        run: |
          pytest --cov=ovos_yes_no_solver --cov-report xml tests